[global]
host = prod-ipa-0.home.arpa
basedn = dc=home,dc=arpa
realm = HOME.ARPA
domain = home.arpa
xmlrpc_uri = https://prod-ipa-0.home.arpa/ipa/xml
ldap_uri = ldapi://%2Frun%2Fslapd-HOME-ARPA.socket
mode = production
enable_ra = True
ra_plugin = dogtag
dogtag_version = 10
startup_timeout = 90

