#File modified by ipa-client-install

includedir /etc/krb5.conf.d/
[libdefaults]
  default_realm = HOME.ARPA
  dns_lookup_realm = false
  rdns = false
  dns_canonicalize_hostname = false
  dns_lookup_kdc = true
  ticket_lifetime = 24h
  forwardable = true
  udp_preference_limit = 0
  default_ccache_name = KEYRING:persistent:%{uid}


[realms]
  HOME.ARPA = {
    kdc = mikoshi.home.arpa:88
    master_kdc = mikoshi.home.arpa:88
    admin_server = mikoshi.home.arpa:749
    kpasswd_server = mikoshi.home.arpa:464
    default_domain = home.arpa
    pkinit_anchors = FILE:/var/lib/ipa-client/pki/kdc-ca-bundle.pem
    pkinit_pool = FILE:/var/lib/ipa-client/pki/ca-bundle.pem

  }


[domain_realm]
  .home.arpa = HOME.ARPA
  home.arpa = HOME.ARPA
  netwatch.home.arpa = HOME.ARPA


