[domain/home.arpa]

id_provider = ipa
ipa_server_mode = True
ipa_server = mikoshi.home.arpa
ipa_domain = home.arpa
ipa_hostname = mikoshi.home.arpa
auth_provider = ipa
chpass_provider = ipa
access_provider = ipa
cache_credentials = True
ldap_tls_cacert = /etc/ipa/ca.crt
krb5_store_password_if_offline = True
[sssd]
services = nss, pam, ifp, ssh, sudo

domains = home.arpa
[nss]
homedir_substring = /home
memcache_timeout = 600

[pam]

[sudo]

[autofs]

[ssh]

[pac]

[ifp]
allowed_uids = ipaapi, root

[session_recording]

