apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arpatek-dev
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - arpatek.dev
      secretName: arpatek-dev-tls
  rules:
    - host: arpatek.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: arpatek-dev
                port:
                  number: 8000
